services:
  website:
    build:
      context: .
      target: prod
    container_name: michelin_website_prod
    restart: always
    ports:
      - "80:80"
    # If you need to override nginx config, uncomment and mount:
    # volumes:
    #   - ./nginx.conf:/etc/nginx/conf.d/default.conf
