baseURL = 'https://example.org/'
title = 'PS-Sport Sport Tires'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    languageName = 'English'
    weight = 1

  [languages.pl]
    languageName = 'Polski'
    weight = 2
