baseURL = '/'
title = 'PS-Sport Sport Tires'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false

[languages]
  [languages.en]
    languageName = 'English'
    weight = 1

  [languages.pl]
    languageName = 'Polski'
    weight = 2
